export const sharedCatalogColumns = [
  'id',
  'name',
  'slug',
  'description',
  'long_desc',
  'categories',
  'gender',
  'styles',
  'motifs',
  'metals',
  'metal_options',
  'stone_types',
  'stone_type_options',
  'stone_weight',
  'stone_weight_range',
  'metal_weight_range',
  'takeaways',
  'translation_notes',
  'design_code',
  'cut',
  'clarity',
  'color',
  'carat',
  'is_active',
  'is_featured',
  'tags'
] as const;
