DELETE FROM site_config;
INSERT OR REPLACE INTO site_config (key, value, updated_at) VALUES ('meta_title', 'Heerawalla | Fine jewelry crafted with precision', datetime('now'));
INSERT OR REPLACE INTO site_config (key, value, updated_at) VALUES ('meta_description', 'Discover Heerawalla''s inspirational fine jewelry - ethical stones, precious metals, and timeless minimal silhouettes.', datetime('now'));
INSERT OR REPLACE INTO site_config (key, value, updated_at) VALUES ('hero_title', 'Heirloom pieces for modern collectors', datetime('now'));
INSERT OR REPLACE INTO site_config (key, value, updated_at) VALUES ('hero_subtitle', 'Hand-finished gold, diamonds, and precious stones with timeless minimalism.', datetime('now'));
INSERT OR REPLACE INTO site_config (key, value, updated_at) VALUES ('hero_cta_label', 'View collections', datetime('now'));
INSERT OR REPLACE INTO site_config (key, value, updated_at) VALUES ('hero_cta_link', '/collections', datetime('now'));
INSERT OR REPLACE INTO site_config (key, value, updated_at) VALUES ('contact_email', 'support@heerawalla.com', datetime('now'));
INSERT OR REPLACE INTO site_config (key, value, updated_at) VALUES ('webmail_compose_url', 'https://mail.google.com/mail/?view=cm&fs=1&to=', datetime('now'));
INSERT OR REPLACE INTO site_config (key, value, updated_at) VALUES ('newsletter_email', 'info@heerawalla.com', datetime('now'));
INSERT OR REPLACE INTO site_config (key, value, updated_at) VALUES ('newsletter_subject', 'Join Heerawalla', datetime('now'));
INSERT OR REPLACE INTO site_config (key, value, updated_at) VALUES ('newsletter_body', 'Please add me to the Heerawalla list.', datetime('now'));
INSERT OR REPLACE INTO site_config (key, value, updated_at) VALUES ('orders_email', 'orders@heerawalla.com', datetime('now'));
INSERT OR REPLACE INTO site_config (key, value, updated_at) VALUES ('consultation_booking_link', 'https://calendar.google.com/calendar/appointments/schedules/AcZssZ0syAfIydQJsRwm2FovSPItSvwSQFRmytbKkOYUj5kUiPHhjOR2C_G90dnkPZk5c3np6Z7oZxj-?gv=true', datetime('now'));
INSERT OR REPLACE INTO site_config (key, value, updated_at) VALUES ('calendar_api_base', 'https://admin-api.heerawalla.com/calendar', datetime('now'));
INSERT OR REPLACE INTO site_config (key, value, updated_at) VALUES ('atelier_api_base', 'https://admin-api.heerawalla.com', datetime('now'));
INSERT OR REPLACE INTO site_config (key, value, updated_at) VALUES ('consultation_fee_mode', 'free', datetime('now'));
INSERT OR REPLACE INTO site_config (key, value, updated_at) VALUES ('about_title', 'About Heerawalla', datetime('now'));
INSERT OR REPLACE INTO site_config (key, value, updated_at) VALUES ('about_description', 'Heerawalla crafts minimal, luxurious jewelry with ethical sourcing and meticulous finishing.', datetime('now'));
INSERT OR REPLACE INTO site_config (key, value, updated_at) VALUES ('order_confirmation_api_base', 'https://admin-api.heerawalla.com', datetime('now'));
INSERT OR REPLACE INTO site_config (key, value, updated_at) VALUES ('order_cancel_api_base', 'https://admin-api.heerawalla.com', datetime('now'));
INSERT OR REPLACE INTO site_config (key, value, updated_at) VALUES ('order_authenticity_api_base', 'https://admin-api.heerawalla.com', datetime('now'));
INSERT OR REPLACE INTO site_config (key, value, updated_at) VALUES ('quote_api_base', 'https://admin-api.heerawalla.com', datetime('now'));