PRAGMA foreign_keys = OFF;
DELETE FROM catalog_media;
DELETE FROM media_library;
PRAGMA foreign_keys = ON;
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_men_bands_hw-001_img-1', 'http://localhost:8787/media/library/products_men_bands_hw-001_img-1.jpeg', 'image', '1', '1', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hw-001', 'products_men_bands_hw-001_img-1', '', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_men_bands_hw-002_img-1', 'http://localhost:8787/media/library/products_men_bands_hw-002_img-1.jpeg', 'image', '1', '1', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hw-002', 'products_men_bands_hw-002_img-1', '', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_men_sets_hms-001_img-bracelet-1', 'http://localhost:8787/media/library/products_men_sets_hms-001_img-bracelet-1.png', 'image', 'bracelet-1', 'The bracelet traces the wrist with a clean line and measured brilliance. It maintains the Axis cadence without excess.', 'The bracelet traces the wrist with a clean line and measured brilliance. It maintains the Axis cadence without excess.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hms-001', 'products_men_sets_hms-001_img-bracelet-1', 'bracelet', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_men_sets_hms-001_img-bracelet-2', 'http://localhost:8787/media/library/products_men_sets_hms-001_img-bracelet-2.jpeg', 'image', 'bracelet-2', 'A second bracelet view emphasizes the linear profile and restrained diamond cadence that define the Axis signature.', 'A second bracelet view emphasizes the linear profile and restrained diamond cadence that define the Axis signature.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hms-001', 'products_men_sets_hms-001_img-bracelet-2', 'bracelet', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_men_sets_hms-001_img-hero-1', 'http://localhost:8787/media/library/products_men_sets_hms-001_img-hero-1.png', 'image', 'hero-1', 'Axis composition in the Men''s Edition. Structured lines and restrained diamonds create a steady, grounded presence.', 'Axis composition in the Men''s Edition. Structured lines and restrained diamonds create a steady, grounded presence.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hms-001', 'products_men_sets_hms-001_img-hero-1', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_men_sets_hms-001_img-pendant-1', 'http://localhost:8787/media/library/products_men_sets_hms-001_img-pendant-1.png', 'image', 'pendant-1', 'The pendant carries Axis with a centered focal point and precise alignment of diamonds. Its presence is calm and architectural.', 'The pendant carries Axis with a centered focal point and precise alignment of diamonds. Its presence is calm and architectural.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hms-001', 'products_men_sets_hms-001_img-pendant-1', 'pendant', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_men_sets_hms-001_img-ring-1', 'http://localhost:8787/media/library/products_men_sets_hms-001_img-ring-1.png', 'image', 'ring-1', 'The composition reads as a quiet statement, anchored by symmetry and balance. It is direct, refined, and enduring.', 'The composition reads as a quiet statement, anchored by symmetry and balance. It is direct, refined, and enduring.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hms-001', 'products_men_sets_hms-001_img-ring-1', 'ring', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_men_sets_hms-002_img-bracelet-1', 'http://localhost:8787/media/library/products_men_sets_hms-002_img-bracelet-1.jpeg', 'image', 'bracelet-1', 'The bracelet echo Eclipse · Sovereign with controlled brilliance and a decisive silhouette. A refined accent, never excessive.', 'The bracelet echo Eclipse · Sovereign with controlled brilliance and a decisive silhouette. A refined accent, never excessive.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hms-002', 'products_men_sets_hms-002_img-bracelet-1', 'bracelet', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_men_sets_hms-002_img-hero-1', 'http://localhost:8787/media/library/products_men_sets_hms-002_img-hero-1.jpeg', 'image', 'hero-1', 'Eclipse - Sovereign in the Men''s Edition. A wealthy, bold presence defined by heavy gold: bracelet, pendant, chain, and ring—solid, commanding, and unapologetic.', 'Eclipse - Sovereign in the Men''s Edition. A wealthy, bold presence defined by heavy gold: bracelet, pendant, chain, and ring—solid, commanding, and unapologetic.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hms-002', 'products_men_sets_hms-002_img-hero-1', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_men_sets_hms-002_img-pendant-1', 'http://localhost:8787/media/library/products_men_sets_hms-002_img-pendant-1.jpeg', 'image', 'pendant-1', 'The pendant carries Eclipse · Sovereign with a centered solitaire and measured tension. The light stays crisp and deliberate.', 'The pendant carries Eclipse · Sovereign with a centered solitaire and measured tension. The light stays crisp and deliberate.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hms-002', 'products_men_sets_hms-002_img-pendant-1', 'pendant', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_men_sets_hms-002_img-ring-1', 'http://localhost:8787/media/library/products_men_sets_hms-002_img-ring-1.jpeg', 'image', 'ring-1', 'The ring completes Eclipse · Sovereign with a bold solitaire and a precise, architectural band.', 'The ring completes Eclipse · Sovereign with a bold solitaire and a precise, architectural band.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hms-002', 'products_men_sets_hms-002_img-ring-1', 'ring', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_unisex_pendants_hwp-001_img-hero-1', 'http://localhost:8787/media/library/products_unisex_pendants_hwp-001_img-hero-1.jpeg', 'image', 'hero-1', 'Designed for those who value meaning as much as elegance, this pendant is a modern symbol of balance, identity, and quiet confidence. Its refined geometry - defined by a vertical line intersecting a perfect circle - represents alignment, purpose, and continuity, making it more than an accessory; it is a personal signature.

Crafted in polished white gold and accented with a precisely set diamond, the pendant delivers subtle brilliance without excess. Its proportions are intentionally restrained, allowing it to sit naturally at the collarbone and layer effortlessly with other pieces, or stand alone as a statement of refined taste.

This is jewelry designed to be worn daily, collected intentionally, and kept for years.', 'Designed for those who value meaning as much as elegance, this pendant is a modern symbol of balance, identity, and quiet confidence. Its refined geometry - defined by a vertical line intersecting a perfect circle - represents alignment, purpose, and continuity, making it more than an accessory; it is a personal signature.

Crafted in polished white gold and accented with a precisely set diamond, the pendant delivers subtle brilliance without excess. Its proportions are intentionally restrained, allowing it to sit naturally at the collarbone and layer effortlessly with other pieces, or stand alone as a statement of refined taste.

This is jewelry designed to be worn daily, collected intentionally, and kept for years.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hwp-001', 'products_unisex_pendants_hwp-001_img-hero-1', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_unisex_pendants_hwp-001_img-hero-2', 'http://localhost:8787/media/library/products_unisex_pendants_hwp-001_img-hero-2.jpeg', 'image', 'hero-2', 'hero-2', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hwp-001', 'products_unisex_pendants_hwp-001_img-hero-2', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_unisex_pendants_hwp-001_img-pendant-1', 'http://localhost:8787/media/library/products_unisex_pendants_hwp-001_img-pendant-1.jpeg', 'image', 'pendant-1', 'pendant-1', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hwp-001', 'products_unisex_pendants_hwp-001_img-pendant-1', 'pendant', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_unisex_pendants_hwp-001_img-pendant-2', 'http://localhost:8787/media/library/products_unisex_pendants_hwp-001_img-pendant-2.jpeg', 'image', 'pendant-2', 'Designed for those who value meaning as much as elegance, this pendant is a modern symbol of balance, identity, and quiet confidence. Its refined geometry—defined by a vertical line intersecting a perfect circle—represents alignment, purpose, and continuity, making it more than an accessory; it is a personal signature.

Crafted in polished white gold and accented with a precisely set diamond, the pendant delivers subtle brilliance without excess. Its proportions are intentionally restrained, allowing it to sit naturally at the collarbone and layer effortlessly with other pieces, or stand alone as a statement of refined taste.

This is jewelry designed to be worn daily, collected intentionally, and kept for years.', 'Designed for those who value meaning as much as elegance, this pendant is a modern symbol of balance, identity, and quiet confidence. Its refined geometry—defined by a vertical line intersecting a perfect circle—represents alignment, purpose, and continuity, making it more than an accessory; it is a personal signature.

Crafted in polished white gold and accented with a precisely set diamond, the pendant delivers subtle brilliance without excess. Its proportions are intentionally restrained, allowing it to sit naturally at the collarbone and layer effortlessly with other pieces, or stand alone as a statement of refined taste.

This is jewelry designed to be worn daily, collected intentionally, and kept for years.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hwp-001', 'products_unisex_pendants_hwp-001_img-pendant-2', 'pendant', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_unisex_pendants_hwp-001_img-pendant-3', 'http://localhost:8787/media/library/products_unisex_pendants_hwp-001_img-pendant-3.png', 'image', 'pendant-3', 'Discreetly engraved on the back with the HEERAWALLA authenticity mark, each pendant carries a promise of craftsmanship, originality, and timeless design. Gender-neutral and versatile, it transitions seamlessly from day to evening, casual to formal—making it an essential addition to any pendant collection.', 'Discreetly engraved on the back with the HEERAWALLA authenticity mark, each pendant carries a promise of craftsmanship, originality, and timeless design. Gender-neutral and versatile, it transitions seamlessly from day to evening, casual to formal—making it an essential addition to any pendant collection.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hwp-001', 'products_unisex_pendants_hwp-001_img-pendant-3', 'pendant', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_unisex_pendants_hwp-002_img-hero-03', 'http://localhost:8787/media/library/products_unisex_pendants_hwp-002_img-hero-03.jpeg', 'image', 'hero-03', 'hero-03', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hwp-002', 'products_unisex_pendants_hwp-002_img-hero-03', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_unisex_pendants_hwp-002_img-hero-1', 'http://localhost:8787/media/library/products_unisex_pendants_hwp-002_img-hero-1.png', 'image', 'hero-1', 'This pendant is designed around balance and intention. The circular form symbolizes continuity and wholeness, while the vertical axis introduces purpose, direction, and personal grounding. Together, they create a form that feels calm, centered, and timeless - never loud, yet instantly distinctive.

Worn on the body, it feels natural and personal. The dime-sized scale keeps it subtle enough for everyday wear, while the refined detailing - diamonds set with visible prongs, clean metal planes, and a precision-engraved signature mark - signals craftsmanship and authenticity. The reversible design adds depth: one side offers brilliance and light, the other a minimalist, symbolic expression of identity.

It is deliberately unisex, equally confident on men and women. Not trend-driven, but meaning-driven - something you wear because it resonates, and keep because it becomes part of your story.', 'This pendant is designed around balance and intention. The circular form symbolizes continuity and wholeness, while the vertical axis introduces purpose, direction, and personal grounding. Together, they create a form that feels calm, centered, and timeless - never loud, yet instantly distinctive.

Worn on the body, it feels natural and personal. The dime-sized scale keeps it subtle enough for everyday wear, while the refined detailing - diamonds set with visible prongs, clean metal planes, and a precision-engraved signature mark - signals craftsmanship and authenticity. The reversible design adds depth: one side offers brilliance and light, the other a minimalist, symbolic expression of identity.

It is deliberately unisex, equally confident on men and women. Not trend-driven, but meaning-driven - something you wear because it resonates, and keep because it becomes part of your story.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hwp-002', 'products_unisex_pendants_hwp-002_img-hero-1', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_unisex_pendants_hwp-002_img-hero-2', 'http://localhost:8787/media/library/products_unisex_pendants_hwp-002_img-hero-2.png', 'image', 'hero-2', 'hero-2', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hwp-002', 'products_unisex_pendants_hwp-002_img-hero-2', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_unisex_pendants_hwp-002_img-pendant-02', 'http://localhost:8787/media/library/products_unisex_pendants_hwp-002_img-pendant-02.png', 'image', 'pendant-02', 'pendant-02', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hwp-002', 'products_unisex_pendants_hwp-002_img-pendant-02', 'pendant', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_unisex_pendants_hwp-002_img-pendant-03', 'http://localhost:8787/media/library/products_unisex_pendants_hwp-002_img-pendant-03.png', 'image', 'pendant-03', 'pendant-03', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hwp-002', 'products_unisex_pendants_hwp-002_img-pendant-03', 'pendant', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_pendants_hw-003_img-1', 'http://localhost:8787/media/library/products_women_pendants_hw-003_img-1.png', 'image', '1', 'Defined by pure simplicity and enduring elegance, a single brilliant-cut diamond is secured in a minimal, refined mount that allows maximum light return, keeping the diamond the focal point.

Designed to be age-agnostic and effortlessly versatile, the pendant moves from a first meaningful gift to an everyday signature piece. Balanced proportions and a classic silhouette keep it timeless.

Suspended on a delicate chain, the solitaire rests at the collarbone, ideal for daily wear, layering, or special occasions. It is understated for day and refined for evening.', 'Defined by pure simplicity and enduring elegance, a single brilliant-cut diamond is secured in a minimal, refined mount that allows maximum light return, keeping the diamond the focal point.

Designed to be age-agnostic and effortlessly versatile, the pendant moves from a first meaningful gift to an everyday signature piece. Balanced proportions and a classic silhouette keep it timeless.

Suspended on a delicate chain, the solitaire rests at the collarbone, ideal for daily wear, layering, or special occasions. It is understated for day and refined for evening.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hw-003', 'products_women_pendants_hw-003_img-1', '', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_pendants_hw-003_img-2', 'http://localhost:8787/media/library/products_women_pendants_hw-003_img-2.png', 'image', '2', 'What sets this piece apart is its clean solitaire setting, designed to maximize brilliance while keeping the metal presence minimal—allowing the diamond to remain the unmistakable focal point. Elegant and lightweight, it is crafted for effortless all-day comfort and everyday wear.', 'What sets this piece apart is its clean solitaire setting, designed to maximize brilliance while keeping the metal presence minimal—allowing the diamond to remain the unmistakable focal point. Elegant and lightweight, it is crafted for effortless all-day comfort and everyday wear.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hw-003', 'products_women_pendants_hw-003_img-2', '', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_pendants_hw-003_img-3', 'http://localhost:8787/media/library/products_women_pendants_hw-003_img-3.png', 'image', '3', 'Thoughtfully proportioned and timeless in design, this pendant evolves with her both emotionally and stylistically, becoming a constant through every stage of life. It is a diamond she will never outgrow—because true simplicity, when done perfectly, never fades.', 'Thoughtfully proportioned and timeless in design, this pendant evolves with her both emotionally and stylistically, becoming a constant through every stage of life. It is a diamond she will never outgrow—because true simplicity, when done perfectly, never fades.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hw-003', 'products_women_pendants_hw-003_img-3', '', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_pendants_hw-003_img-4', 'http://localhost:8787/media/library/products_women_pendants_hw-003_img-4.png', 'image', '4', 'The back of the pendant is intentionally clean and refined, designed to let the diamond take center stage without distraction. A minimal open-gallery allows light to flow freely through the stone, enhancing brilliance from every angle while reducing unnecessary metal weight. The discreet, low-profile setting sits flush against the skin for all-day comfort and a seamless look when worn. Every surface is smoothly finished, reflecting thoughtful craftsmanship and a commitment to understated elegance—proof that true luxury is just as beautiful where you don’t immediately look.', 'The back of the pendant is intentionally clean and refined, designed to let the diamond take center stage without distraction. A minimal open-gallery allows light to flow freely through the stone, enhancing brilliance from every angle while reducing unnecessary metal weight. The discreet, low-profile setting sits flush against the skin for all-day comfort and a seamless look when worn. Every surface is smoothly finished, reflecting thoughtful craftsmanship and a commitment to understated elegance—proof that true luxury is just as beautiful where you don’t immediately look.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hw-003', 'products_women_pendants_hw-003_img-4', '', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_pendants_hw-003_img-5', 'http://localhost:8787/media/library/products_women_pendants_hw-003_img-5.png', 'image', '5', 'More than packaging—it’s part of the gift. Each pendant is presented in an elegant keepsake box, designed to elevate the moment it’s given. From the smooth exterior to the plush interior that highlights the diamond’s sparkle, the experience feels intentional, personal, and meaningful. Ready to gift, no wrapping required.', 'More than packaging—it’s part of the gift. Each pendant is presented in an elegant keepsake box, designed to elevate the moment it’s given. From the smooth exterior to the plush interior that highlights the diamond’s sparkle, the experience feels intentional, personal, and meaningful. Ready to gift, no wrapping required.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hw-003', 'products_women_pendants_hw-003_img-5', '', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_rings_hw-002_img-hero-1', 'http://localhost:8787/media/library/products_women_rings_hw-002_img-hero-1.png', 'image', 'hero-1', 'hero-1', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hw-002', 'products_women_rings_hw-002_img-hero-1', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_rings_hw-002_img-ring-1', 'http://localhost:8787/media/library/products_women_rings_hw-002_img-ring-1.png', 'image', 'ring-1', 'ring-1', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hw-002', 'products_women_rings_hw-002_img-ring-1', 'ring', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-001_img-bracelet-1', 'http://localhost:8787/media/library/products_women_sets_hws-001_img-bracelet-1.png', 'image', 'bracelet-1', 'The bracelet presents Eclipse as a strong line of light across the wrist. It is bold, composed, and enduring.', 'The bracelet presents Eclipse as a strong line of light across the wrist. It is bold, composed, and enduring.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-001', 'products_women_sets_hws-001_img-bracelet-1', 'bracelet', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-001_img-earring-1', 'http://localhost:8787/media/library/products_women_sets_hws-001_img-earring-1.png', 'image', 'earring-1', 'The earrings bring Eclipse to the face with a pronounced glow and a poised outline. The effect is confident, never loud.', 'The earrings bring Eclipse to the face with a pronounced glow and a poised outline. The effect is confident, never loud.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-001', 'products_women_sets_hws-001_img-earring-1', 'ring', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-001_img-hero-1', 'http://localhost:8787/media/library/products_women_sets_hws-001_img-hero-1.png', 'image', 'hero-1', 'Eclipse composition in the Women''s Edition. Concentrated light and bold contrast create a magnetic presence.', 'Eclipse composition in the Women''s Edition. Concentrated light and bold contrast create a magnetic presence.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-001', 'products_women_sets_hws-001_img-hero-1', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-001_img-pendant-1', 'http://localhost:8787/media/library/products_women_sets_hws-001_img-pendant-1.png', 'image', 'pendant-1', 'The pendant distills Eclipse into a luminous focal point with depth held in balance. It feels bold yet controlled.', 'The pendant distills Eclipse into a luminous focal point with depth held in balance. It feels bold yet controlled.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-001', 'products_women_sets_hws-001_img-pendant-1', 'pendant', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-002_img-bracelet-1', 'http://localhost:8787/media/library/products_women_sets_hws-002_img-bracelet-1.png', 'image', 'bracelet-1', 'The bracelet moves with the wrist in a smooth, uninterrupted line. The diamonds read as a quiet stream of light.', 'The bracelet moves with the wrist in a smooth, uninterrupted line. The diamonds read as a quiet stream of light.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-002', 'products_women_sets_hws-002_img-bracelet-1', 'bracelet', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-002_img-earring-1', 'http://localhost:8787/media/library/products_women_sets_hws-002_img-earring-1.png', 'image', 'earring-1', 'The earrings extend the Continuum language with flowing symmetry and an even shimmer. They remain poised and effortless.', 'The earrings extend the Continuum language with flowing symmetry and an even shimmer. They remain poised and effortless.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-002', 'products_women_sets_hws-002_img-earring-1', 'ring', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-002_img-hero-1', 'http://localhost:8787/media/library/products_women_sets_hws-002_img-hero-1.png', 'image', 'hero-1', 'Continuum composition in the Women''s Edition. The diamonds read fluid, graceful, and continuous.', 'Continuum composition in the Women''s Edition. The diamonds read fluid, graceful, and continuous.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-002', 'products_women_sets_hws-002_img-hero-1', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-002_img-pendant-1', 'http://localhost:8787/media/library/products_women_sets_hws-002_img-pendant-1.png', 'image', 'pendant-1', 'The pendant follows the Continuum rhythm with a soft, continuous line and a gentle glow. Its proportions feel light and refined.', 'The pendant follows the Continuum rhythm with a soft, continuous line and a gentle glow. Its proportions feel light and refined.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-002', 'products_women_sets_hws-002_img-pendant-1', 'pendant', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-003_img-bracelet-1', 'http://localhost:8787/media/library/products_women_sets_hws-003_img-bracelet-1.png', 'image', 'bracelet-1', 'The bracelet delivers a steady line of brilliance along the wrist, measured and refined.', 'The bracelet delivers a steady line of brilliance along the wrist, measured and refined.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-003', 'products_women_sets_hws-003_img-bracelet-1', 'bracelet', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-003_img-earring-1', 'http://localhost:8787/media/library/products_women_sets_hws-003_img-earring-1.png', 'image', 'earring-1', 'The earrings reflect Axis through symmetry and clarity, offering a quiet, focused radiance.', 'The earrings reflect Axis through symmetry and clarity, offering a quiet, focused radiance.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-003', 'products_women_sets_hws-003_img-earring-1', 'ring', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-003_img-hero-1', 'http://localhost:8787/media/library/products_women_sets_hws-003_img-hero-1.png', 'image', 'hero-1', 'Axis composition in the Women''s Edition. Anchored geometry meets a clear, confident line of light.', 'Axis composition in the Women''s Edition. Anchored geometry meets a clear, confident line of light.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-003', 'products_women_sets_hws-003_img-hero-1', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-003_img-pendant-1', 'http://localhost:8787/media/library/products_women_sets_hws-003_img-pendant-1.png', 'image', 'pendant-1', 'The pendant centers the Axis language with precise alignment and a balanced glow. It feels composed and architectural.', 'The pendant centers the Axis language with precise alignment and a balanced glow. It feels composed and architectural.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-003', 'products_women_sets_hws-003_img-pendant-1', 'pendant', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-004_img-bracelet-1', 'http://localhost:8787/media/library/products_women_sets_hws-004_img-bracelet-1.png', 'image', 'bracelet-1', 'The bracelet traces the wrist in a smooth arc of light, restrained and continuous.', 'The bracelet traces the wrist in a smooth arc of light, restrained and continuous.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-004', 'products_women_sets_hws-004_img-bracelet-1', 'bracelet', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-004_img-composition-1', 'http://localhost:8787/media/library/products_women_sets_hws-004_img-composition-1.png', 'image', 'composition-1', 'composition-1', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-004', 'products_women_sets_hws-004_img-composition-1', '', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-004_img-earring-1', 'http://localhost:8787/media/library/products_women_sets_hws-004_img-earring-1.png', 'image', 'earring-1', 'The earrings mirror the Continuum flow with clean symmetry and a soft glow.', 'The earrings mirror the Continuum flow with clean symmetry and a soft glow.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-004', 'products_women_sets_hws-004_img-earring-1', 'ring', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-004_img-hero-1', 'http://localhost:8787/media/library/products_women_sets_hws-004_img-hero-1.png', 'image', 'hero-1', 'Continuum composition in the Women''s Edition. Fluid symmetry and a calm line of diamonds define the profile.', 'Continuum composition in the Women''s Edition. Fluid symmetry and a calm line of diamonds define the profile.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-004', 'products_women_sets_hws-004_img-hero-1', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-004_img-pendant-1', 'http://localhost:8787/media/library/products_women_sets_hws-004_img-pendant-1.png', 'image', 'pendant-1', 'The pendant keeps the Continuum cadence with a focused, luminous center. The impression is light and refined.', 'The pendant keeps the Continuum cadence with a focused, luminous center. The impression is light and refined.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-004', 'products_women_sets_hws-004_img-pendant-1', 'pendant', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-004_img-ring-1', 'http://localhost:8787/media/library/products_women_sets_hws-004_img-ring-1.png', 'image', 'ring-1', 'The ring completes the composition with a refined band of brilliance, designed for everyday ease.', 'The ring completes the composition with a refined band of brilliance, designed for everyday ease.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-004', 'products_women_sets_hws-004_img-ring-1', 'ring', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-005_img-bracelet-1', 'http://localhost:8787/media/library/products_women_sets_hws-005_img-bracelet-1.png', 'image', 'bracelet-1', 'The bracelet traces the wrist with an even line of light, staying disciplined and refined. Its presence remains measured and architectural.', 'The bracelet traces the wrist with an even line of light, staying disciplined and refined. Its presence remains measured and architectural.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-005', 'products_women_sets_hws-005_img-bracelet-1', 'bracelet', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-005_img-earring-1', 'http://localhost:8787/media/library/products_women_sets_hws-005_img-earring-1.jpeg', 'image', 'earring-1', 'The earrings echo Axis · Equilibria through balanced proportion and restrained sparkle. The effect is calm and exacting.', 'The earrings echo Axis · Equilibria through balanced proportion and restrained sparkle. The effect is calm and exacting.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-005', 'products_women_sets_hws-005_img-earring-1', 'ring', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-005_img-hero-1', 'http://localhost:8787/media/library/products_women_sets_hws-005_img-hero-1.png', 'image', 'hero-1', 'Axis - Equilibria in the Women''s Edition. Precise alignment and lab-grown diamonds deliver a poised, luminous presence.', 'Axis - Equilibria in the Women''s Edition. Precise alignment and lab-grown diamonds deliver a poised, luminous presence.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-005', 'products_women_sets_hws-005_img-hero-1', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-005_img-pendant-1', 'http://localhost:8787/media/library/products_women_sets_hws-005_img-pendant-1.jpeg', 'image', 'pendant-1', 'The pendant carries Axis · Equilibria with a precise focal line and quiet brilliance. Lab-grown diamonds keep the light clean and controlled.', 'The pendant carries Axis · Equilibria with a precise focal line and quiet brilliance. Lab-grown diamonds keep the light clean and controlled.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-005', 'products_women_sets_hws-005_img-pendant-1', 'pendant', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-005_img-ring-1', 'http://localhost:8787/media/library/products_women_sets_hws-005_img-ring-1.jpeg', 'image', 'ring-1', 'The ring completes the composition with a focused band of brilliance, designed for effortless daily wear.', 'The ring completes the composition with a focused band of brilliance, designed for effortless daily wear.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-005', 'products_women_sets_hws-005_img-ring-1', 'ring', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-006_img-bracelet-1', 'http://localhost:8787/media/library/products_women_sets_hws-006_img-bracelet-1.jpeg', 'image', 'bracelet-1', 'bracelet-1', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-006', 'products_women_sets_hws-006_img-bracelet-1', 'bracelet', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-006_img-earring-1', 'http://localhost:8787/media/library/products_women_sets_hws-006_img-earring-1.jpg', 'image', 'earring-1', 'earring-1', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-006', 'products_women_sets_hws-006_img-earring-1', 'ring', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-006_img-hero-1', 'http://localhost:8787/media/library/products_women_sets_hws-006_img-hero-1.jpeg', 'image', 'hero-1', 'Continuum - Solitaire shown in the Women''s Edition. Lab-grown diamonds flow in a clean, architectural line with a refined finish.', 'Continuum - Solitaire shown in the Women''s Edition. Lab-grown diamonds flow in a clean, architectural line with a refined finish.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-006', 'products_women_sets_hws-006_img-hero-1', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-006_img-pendant-1', 'http://localhost:8787/media/library/products_women_sets_hws-006_img-pendant-1.png', 'image', 'pendant-1', 'pendant-1', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-006', 'products_women_sets_hws-006_img-pendant-1', 'pendant', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-006_img-ring-1', 'http://localhost:8787/media/library/products_women_sets_hws-006_img-ring-1.jpeg', 'image', 'ring-1', 'ring-1', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-006', 'products_women_sets_hws-006_img-ring-1', 'ring', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-007_img-bracelet-1', 'http://localhost:8787/media/library/products_women_sets_hws-007_img-bracelet-1.jpeg', 'image', 'bracelet-1', 'Slim bangle with a crossing pave motif, polished and balanced to Heerawalla standards.', 'Slim bangle with a crossing pave motif, polished and balanced to Heerawalla standards.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-007', 'products_women_sets_hws-007_img-bracelet-1', 'bracelet', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-007_img-earring-1', 'http://localhost:8787/media/library/products_women_sets_hws-007_img-earring-1.jpeg', 'image', 'earring-1', 'Twisted leaf earrings (variant) with a single pave ribbon for light and length. Balanced curves and clean edges, finished to Heerawalla standards.', 'Twisted leaf earrings (variant) with a single pave ribbon for light and length. Balanced curves and clean edges, finished to Heerawalla standards.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-007', 'products_women_sets_hws-007_img-earring-1', 'ring', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-007_img-engraving-1', 'http://localhost:8787/media/library/products_women_sets_hws-007_img-engraving-1.png', 'image', 'engraving-1', 'Heerawalla signature engraving, a discreet mark of origin and finishing standards.', 'Heerawalla signature engraving, a discreet mark of origin and finishing standards.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-007', 'products_women_sets_hws-007_img-engraving-1', '', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-007_img-hero-1', 'http://localhost:8787/media/library/products_women_sets_hws-007_img-hero-1.png', 'image', 'hero-1', 'Continuum composition in 18K gold, the twist motif moving through earrings, pendant, ring, and bracelet with a clean pave line. Finished to Heerawalla standards of proportion, polish, and balance.', 'Continuum composition in 18K gold, the twist motif moving through earrings, pendant, ring, and bracelet with a clean pave line. Finished to Heerawalla standards of proportion, polish, and balance.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-007', 'products_women_sets_hws-007_img-hero-1', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-007_img-pendant-1', 'http://localhost:8787/media/library/products_women_sets_hws-007_img-pendant-1.png', 'image', 'pendant-1', 'A fluid pendant with a sculpted twist and pave spine, suspended on a fine chain. Proportions stay light, precise, and refined.', 'A fluid pendant with a sculpted twist and pave spine, suspended on a fine chain. Proportions stay light, precise, and refined.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-007', 'products_women_sets_hws-007_img-pendant-1', 'pendant', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-007_img-ring-1', 'http://localhost:8787/media/library/products_women_sets_hws-007_img-ring-1.png', 'image', 'ring-1', 'Double-band ring crossing into a pave wave, engineered for a smooth, continuous line. Polished to Heerawalla standards of balance and finish.', 'Double-band ring crossing into a pave wave, engineered for a smooth, continuous line. Polished to Heerawalla standards of balance and finish.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-007', 'products_women_sets_hws-007_img-ring-1', 'ring', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-008_img-earring-1', 'http://localhost:8787/media/library/products_women_sets_hws-008_img-earring-1.jpeg', 'image', 'earring-1', 'The design feels fluid and intentional, built around motion rather than ornament. Its silhouette rises gently, suggesting growth, confidence, and self-possession, while the diamonds are restrained—used to create a soft, continuous glow instead of dramatic sparkle. Nothing feels excessive; every element has a purpose.

On the wearer, the jewelry reads as personal and refined. The pendant sits naturally, almost like a signature, and the earrings echo the same language with lightness and balance. Together, they feel contemporary, feminine, and composed—luxury that speaks through proportion, craftsmanship, and calm confidence rather than bold display.

It’s a piece that feels owned, not showcased.', 'The design feels fluid and intentional, built around motion rather than ornament. Its silhouette rises gently, suggesting growth, confidence, and self-possession, while the diamonds are restrained—used to create a soft, continuous glow instead of dramatic sparkle. Nothing feels excessive; every element has a purpose.

On the wearer, the jewelry reads as personal and refined. The pendant sits naturally, almost like a signature, and the earrings echo the same language with lightness and balance. Together, they feel contemporary, feminine, and composed—luxury that speaks through proportion, craftsmanship, and calm confidence rather than bold display.

It’s a piece that feels owned, not showcased.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-008', 'products_women_sets_hws-008_img-earring-1', 'ring', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-008_img-hero-1', 'http://localhost:8787/media/library/products_women_sets_hws-008_img-hero-1.jpeg', 'image', 'hero-1', 'A study in quiet elegance, this diamond pendant and earring set celebrates feminine strength through fluid form and restrained brilliance. Sculpted in polished white gold, the design traces a graceful, upward silhouette - symbolic of confidence, movement, and self-expression - while pave-set diamonds add a soft, luminous shimmer rather than overt sparkle.

Worn close to the skin, the pendant rests delicately at the collarbone, balanced by subtly scaled drop earrings that frame the face without overpowering it. The proportions are intentionally refined, making the set equally suited for elevated daytime wear or understated evening elegance.

Finished with a discreet engraved signature mark, the piece reflects craftsmanship, authenticity, and modern luxury - designed not to command attention, but to reward it.', 'A study in quiet elegance, this diamond pendant and earring set celebrates feminine strength through fluid form and restrained brilliance. Sculpted in polished white gold, the design traces a graceful, upward silhouette - symbolic of confidence, movement, and self-expression - while pave-set diamonds add a soft, luminous shimmer rather than overt sparkle.

Worn close to the skin, the pendant rests delicately at the collarbone, balanced by subtly scaled drop earrings that frame the face without overpowering it. The proportions are intentionally refined, making the set equally suited for elevated daytime wear or understated evening elegance.

Finished with a discreet engraved signature mark, the piece reflects craftsmanship, authenticity, and modern luxury - designed not to command attention, but to reward it.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-008', 'products_women_sets_hws-008_img-hero-1', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('products_women_sets_hws-008_img-pendant-1', 'http://localhost:8787/media/library/products_women_sets_hws-008_img-pendant-1.jpeg', 'image', 'pendant-1', 'This design expresses modern femininity through movement and restraint. The flowing silhouette suggests grace and confidence, while the upward sweep conveys quiet strength and optimism. Diamonds are used with intention—softly pavé-set to create luminosity rather than excess—allowing the form to lead and the brilliance to follow.

The scale is refined and wearable, designed to feel personal rather than performative. On the body, the pendant rests naturally at the collarbone, while the earrings frame the face with lightness and poise. The overall impression is elegant, contemporary, and self-assured—luxury that feels lived-in, not ceremonial.

It is a piece meant to be noticed slowly, appreciated up close, and worn as an extension of the wearer rather than a statement over her.', 'This design expresses modern femininity through movement and restraint. The flowing silhouette suggests grace and confidence, while the upward sweep conveys quiet strength and optimism. Diamonds are used with intention—softly pavé-set to create luminosity rather than excess—allowing the form to lead and the brilliance to follow.

The scale is refined and wearable, designed to feel personal rather than performative. On the body, the pendant rests naturally at the collarbone, while the earrings frame the face with lightness and poise. The overall impression is elegant, contemporary, and self-assured—luxury that feels lived-in, not ceremonial.

It is a piece meant to be noticed slowly, appreciated up close, and worn as an extension of the wearer rather than a statement over her.', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('hws-008', 'products_women_sets_hws-008_img-pendant-1', 'pendant', 0, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('inspirations_insp-0001', 'http://localhost:8787/media/library/inspirations_insp-0001.jpeg', 'image', 'insp-0001', 'insp-0001', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('insp-0001', 'inspirations_insp-0001', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('inspirations_insp-0002', 'http://localhost:8787/media/library/inspirations_insp-0002.jpeg', 'image', 'insp-0002', 'insp-0002', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('insp-0002', 'inspirations_insp-0002', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('inspirations_insp-0003', 'http://localhost:8787/media/library/inspirations_insp-0003.jpeg', 'image', 'insp-0003', 'insp-0003', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('insp-0003', 'inspirations_insp-0003', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('inspirations_insp-0004', 'http://localhost:8787/media/library/inspirations_insp-0004.png', 'image', 'insp-0004', 'insp-0004', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('insp-0004', 'inspirations_insp-0004', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('inspirations_insp-0005', 'http://localhost:8787/media/library/inspirations_insp-0005.png', 'image', 'insp-0005', 'insp-0005', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('insp-0005', 'inspirations_insp-0005', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('inspirations_insp-0006', 'http://localhost:8787/media/library/inspirations_insp-0006.png', 'image', 'insp-0006', 'insp-0006', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('insp-0006', 'inspirations_insp-0006', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('inspirations_insp-0007', 'http://localhost:8787/media/library/inspirations_insp-0007.png', 'image', 'insp-0007', 'insp-0007', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('insp-0007', 'inspirations_insp-0007', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('inspirations_insp-0008', 'http://localhost:8787/media/library/inspirations_insp-0008.jpeg', 'image', 'insp-0008', 'insp-0008', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('insp-0008', 'inspirations_insp-0008', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('inspirations_insp-0009', 'http://localhost:8787/media/library/inspirations_insp-0009.jpeg', 'image', 'insp-0009', 'insp-0009', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('insp-0009', 'inspirations_insp-0009', 'hero', 1, 0);
INSERT INTO media_library (media_id, url, media_type, label, alt, description, created_at) VALUES ('inspirations_insp-0010', 'http://localhost:8787/media/library/inspirations_insp-0010.png', 'image', 'insp-0010', 'insp-0010', '', datetime('now')) ON CONFLICT(media_id) DO UPDATE SET url = excluded.url, media_type = excluded.media_type, label = excluded.label, alt = excluded.alt, description = excluded.description;
INSERT INTO catalog_media (catalog_id, media_id, position, is_primary, sort_order) VALUES ('insp-0010', 'inspirations_insp-0010', 'hero', 1, 0);
