PRAGMA foreign_keys = OFF;

CREATE TABLE catalog_items_new (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('product', 'inspiration')),
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  long_desc TEXT,
  hero_image TEXT,
  collection TEXT,
  categories TEXT,
  gender TEXT,
  styles TEXT,
  motifs TEXT,
  metals TEXT,
  stone_types TEXT,
  stone_weight TEXT,
  metal_weight TEXT,
  palette TEXT,
  design_code TEXT,
  cut TEXT,
  cut_range TEXT,
  clarity TEXT,
  clarity_range TEXT,
  color TEXT,
  color_range TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  is_featured INTEGER NOT NULL DEFAULT 0,
  tags TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_by TEXT
);

INSERT INTO catalog_items_new (
  id,
  type,
  name,
  slug,
  description,
  long_desc,
  hero_image,
  collection,
  categories,
  gender,
  styles,
  motifs,
  metals,
  stone_types,
  stone_weight,
  metal_weight,
  palette,
  design_code,
  cut,
  cut_range,
  clarity,
  clarity_range,
  color,
  color_range,
  is_active,
  is_featured,
  tags,
  created_at,
  updated_at,
  updated_by
)
SELECT
  id,
  type,
  name,
  slug,
  description,
  long_desc,
  hero_image,
  collection,
  categories,
  gender,
  styles,
  motifs,
  metals,
  stone_types,
  stone_weight,
  metal_weight,
  palette,
  design_code,
  cut,
  cut_range,
  clarity,
  clarity_range,
  color,
  color_range,
  is_active,
  is_featured,
  tags,
  created_at,
  updated_at,
  updated_by
FROM catalog_items;

DROP TABLE catalog_items;
ALTER TABLE catalog_items_new RENAME TO catalog_items;

CREATE INDEX IF NOT EXISTS idx_catalog_items_type_active
  ON catalog_items (type, is_active, is_featured);

PRAGMA foreign_keys = ON;
