export const STATUS_OPTIONS = {
  orders: [
    "NEW",
    "ACKNOWLEDGED",
    "PENDING_CONFIRMATION",
    "INVOICED",
    "INVOICE_EXPIRED",
    "INVOICE_PAID",
    "PROCESSING",
    "SHIPPED",
    "DELIVERED",
    "CANCELLED",
  ],
  quotes: ["NEW", "ACKNOWLEDGED", "QUOTED", "QUOTE_ACTIONED", "DROPPED"],
  tickets: ["NEW", "PENDING", "RESOLVED"],
  contacts: [],
  products: [],
  inspirations: [],
  "media-library": [],
  "cost-chart": [],
  "diamond-price-chart": [],
};

export const LIST_COLUMNS = {
  orders: [
    { key: "created_at", label: "Created" },
    { key: "request_id", label: "Request ID" },
    { key: "product_name", label: "Product" },
    { key: "status", label: "Status" },
    { key: "price", label: "Price" },
    { key: "timeline", label: "Timeline" },
    { key: "view", label: "" },
    { key: "delete", label: "" },
  ],
  quotes: [
    { key: "created_at", label: "Created" },
    { key: "request_id", label: "Request ID" },
    { key: "product_name", label: "Product" },
    { key: "status", label: "Status" },
    { key: "price", label: "Price" },
    { key: "timeline", label: "Timeline" },
    { key: "view", label: "" },
    { key: "delete", label: "" },
  ],
  tickets: [
    { key: "created_at", label: "Created" },
    { key: "request_id", label: "Request ID" },
    { key: "name", label: "Name" },
    { key: "email", label: "Email" },
    { key: "status", label: "Status" },
    { key: "subject", label: "Subject" },
    { key: "summary", label: "Summary" },
    { key: "view", label: "" },
    { key: "delete", label: "" },
  ],
  contacts: [
    { key: "created_at", label: "Created" },
    { key: "name", label: "Name" },
    { key: "email", label: "Email" },
    { key: "phone", label: "Phone" },
    { key: "source", label: "Source" },
    { key: "request_id", label: "Request ID" },
    { key: "view", label: "" },
  ],
  products: [
    { key: "id", label: "ID" },
    { key: "name", label: "Name" },
    { key: "slug", label: "Slug" },
    { key: "category", label: "Category" },
    { key: "design_code", label: "Design code" },
    { key: "is_active", label: "Active" },
    { key: "view", label: "" },
    { key: "delete", label: "" },
  ],
  inspirations: [
    { key: "id", label: "ID" },
    { key: "name", label: "Name" },
    { key: "slug", label: "Slug" },
    { key: "categories", label: "Category" },
    { key: "design_code", label: "Design code" },
    { key: "is_active", label: "Active" },
    { key: "view", label: "" },
  ],
  "media-library": [
    { key: "media_id", label: "Media ID" },
    { key: "label", label: "Label" },
    { key: "media_type", label: "Type" },
    { key: "url", label: "Preview" },
    { key: "view", label: "" },
  ],
  "cost-chart": [
    { key: "row_number", label: "Row" },
    { key: "key", label: "Key" },
    { key: "value", label: "Value" },
    { key: "unit", label: "Unit" },
    { key: "notes", label: "Notes" },
    { key: "view", label: "" },
  ],
  "diamond-price-chart": [
    { key: "row_number", label: "Row" },
    { key: "clarity", label: "Clarity" },
    { key: "color", label: "Color" },
    { key: "weight_min", label: "Min ct" },
    { key: "weight_max", label: "Max ct" },
    { key: "price_per_ct", label: "Price/ct" },
    { key: "view", label: "" },
  ],
};

export const SORT_OPTIONS = {
  orders: [
    { value: "created_at", label: "Created" },
    { value: "status", label: "Status" },
    { value: "price", label: "Price" },
    { value: "timeline", label: "Timeline" },
    { value: "name", label: "Name" },
    { value: "request_id", label: "Request ID" },
  ],
  quotes: [
    { value: "created_at", label: "Created" },
    { value: "status", label: "Status" },
    { value: "price", label: "Price" },
    { value: "timeline", label: "Timeline" },
    { value: "name", label: "Name" },
    { value: "request_id", label: "Request ID" },
  ],
  tickets: [
    { value: "created_at", label: "Created" },
    { value: "status", label: "Status" },
    { value: "name", label: "Name" },
    { value: "email", label: "Email" },
    { value: "subject", label: "Subject" },
  ],
  contacts: [
    { value: "created_at", label: "Created" },
    { value: "name", label: "Name" },
    { value: "email", label: "Email" },
    { value: "source", label: "Source" },
  ],
  products: [
    { value: "name", label: "Name" },
    { value: "slug", label: "Slug" },
    { value: "category", label: "Category" },
    { value: "design_code", label: "Design code" },
    { value: "is_active", label: "Active" },
  ],
  inspirations: [
    { value: "name", label: "Name" },
    { value: "slug", label: "Slug" },
    { value: "categories", label: "Category" },
    { value: "design_code", label: "Design code" },
    { value: "is_active", label: "Active" },
  ],
  "media-library": [
    { value: "media_id", label: "Media ID" },
    { value: "label", label: "Label" },
    { value: "media_type", label: "Type" },
  ],
  "cost-chart": [
    { value: "row_number", label: "Row" },
    { value: "key", label: "Key" },
    { value: "value", label: "Value" },
  ],
  "diamond-price-chart": [
    { value: "row_number", label: "Row" },
    { value: "clarity", label: "Clarity" },
    { value: "color", label: "Color" },
    { value: "weight_min", label: "Min ct" },
    { value: "price_per_ct", label: "Price/ct" },
  ],
};

export const SORT_DEFAULTS = {
  orders: { sort: "created_at", dir: "desc" },
  quotes: { sort: "created_at", dir: "desc" },
  tickets: { sort: "created_at", dir: "desc" },
  contacts: { sort: "created_at", dir: "desc" },
  products: { sort: "name", dir: "asc" },
  inspirations: { sort: "name", dir: "asc" },
  "media-library": { sort: "media_id", dir: "asc" },
  "cost-chart": { sort: "row_number", dir: "asc" },
  "diamond-price-chart": { sort: "row_number", dir: "asc" },
};

export const ACTIONS = {
  orders: [
    { action: "acknowledge", label: "Acknowledge", confirm: "Mark as acknowledged?" },
    { action: "send_invoice", label: "Send invoice", confirm: "Send invoice and mark invoiced?" },
    { action: "mark_paid", label: "Mark paid", confirm: "Confirm payment received?" },
    { action: "mark_invoice_expired", label: "Mark invoice expired", confirm: "Mark invoice as expired?" },
    { action: "mark_processing", label: "Mark processing", confirm: "Move order into processing?" },
    { action: "mark_shipped", label: "Mark shipped", confirm: "Mark as shipped?" },
    { action: "mark_delivered", label: "Mark delivered", confirm: "Mark as delivered?" },
    { action: "cancel", label: "Cancel order", confirm: "Cancel this order?" },
    { action: "delete", label: "Delete", confirm: "Delete this order? This cannot be undone." },
  ],
  quotes: [
    { action: "acknowledge", label: "Acknowledge", confirm: "Mark as acknowledged?" },
    { action: "submit_quote", label: "Send quote link", confirm: "Send quote link to customer?" },
    { action: "refresh_quote", label: "Refresh quote link", confirm: "Send a refreshed quote link?" },
    { action: "mark_actioned", label: "Mark quote actioned", confirm: "Mark quote as actioned?" },
    { action: "drop", label: "Drop", confirm: "Drop this quote?" },
    { action: "delete", label: "Delete", confirm: "Delete this quote? This cannot be undone." },
  ],
  tickets: [
    { action: "mark_pending", label: "Mark pending", confirm: "Mark as pending?" },
    { action: "mark_resolved", label: "Mark resolved", confirm: "Mark as resolved?" },
    { action: "delete", label: "Delete", confirm: "Delete this ticket? This cannot be undone." },
  ],
  contacts: [],
  products: [{ action: "delete", label: "Delete", confirm: "Delete this product? This cannot be undone." }],
  inspirations: [],
  "media-library": [],
  "cost-chart": [],
  "diamond-price-chart": [],
};

export const EDIT_FIELDS = {
  orders: [
    "price",
    "timeline",
    "timeline_adjustment_weeks",
    "metal",
    "metal_weight",
    "metal_weight_adjustment",
    "stone",
    "stone_weight",
    "notes",
  ],
  quotes: [
    "price",
    "timeline",
    "timeline_adjustment_weeks",
    "metal",
    "metal_weight",
    "stone",
    "stone_weight",
    "diamond_breakdown",
    "size",
    "quote_metal_options",
    "quote_option_1_clarity",
    "quote_option_1_color",
    "quote_option_1_price_18k",
    "quote_option_2_clarity",
    "quote_option_2_color",
    "quote_option_2_price_18k",
    "quote_option_3_clarity",
    "quote_option_3_color",
    "quote_option_3_price_18k",
    "quote_discount_type",
    "quote_discount_percent",
    "notes",
  ],
  tickets: ["notes"],
  contacts: [],
  products: [],
  inspirations: [],
  "media-library": [],
  "cost-chart": ["key", "value", "unit", "notes"],
  "diamond-price-chart": ["clarity", "color", "weight_min", "weight_max", "price_per_ct", "notes"],
};

export const ORDER_DETAILS_FIELDS = [
  "shipping_method",
  "shipping_carrier",
  "tracking_number",
  "tracking_url",
  "shipping_status",
  "delivery_eta",
  "shipping_notes",
  "certificates",
  "care_details",
  "warranty_details",
  "service_details",
];

export const REQUIRED_SHIPPING_DETAILS_FIELDS = [
  "shipping_carrier",
  "tracking_number",
  "certificates",
  "care_details",
  "warranty_details",
  "service_details",
];

export const ORDER_STATUS_FLOW = {
  NEW: ["ACKNOWLEDGED", "CANCELLED"],
  ACKNOWLEDGED: ["PENDING_CONFIRMATION", "INVOICED", "CANCELLED"],
  PENDING_CONFIRMATION: ["INVOICED", "CANCELLED"],
  INVOICED: ["INVOICE_PAID", "INVOICE_EXPIRED", "CANCELLED"],
  INVOICE_EXPIRED: ["INVOICED", "CANCELLED"],
  INVOICE_PAID: ["PROCESSING", "SHIPPED"],
  PROCESSING: ["SHIPPED"],
  SHIPPED: ["DELIVERED"],
  DELIVERED: [],
  CANCELLED: ["INVOICED"],
};

export const ORDER_ACTION_FLOW = {
  NEW: ["acknowledge", "cancel"],
  ACKNOWLEDGED: ["send_invoice", "cancel"],
  PENDING_CONFIRMATION: ["send_invoice", "cancel"],
  INVOICED: ["mark_paid", "mark_invoice_expired", "cancel"],
  INVOICE_EXPIRED: ["send_invoice", "cancel"],
  INVOICE_PAID: ["mark_processing", "mark_shipped"],
  PROCESSING: ["mark_shipped"],
  SHIPPED: ["mark_delivered"],
  DELIVERED: [],
  CANCELLED: ["send_invoice"],
};

export const TAB_LABELS = {
  orders: "Order",
  quotes: "Quote",
  tickets: "Customer ticket",
  contacts: "Contact",
  products: "Product",
  inspirations: "Inspiration",
  "media-library": "Media library",
  "cost-chart": "Cost chart",
  "diamond-price-chart": "Diamond price chart",
};

export const PRICING_TABS = new Set(["cost-chart", "diamond-price-chart"]);
export const CATALOG_TABS = new Set(["products", "inspirations", "media-library"]);

export const QUOTE_OPTION_FIELDS = [
  { clarity: "quote_option_1_clarity", color: "quote_option_1_color", price: "quote_option_1_price_18k" },
  { clarity: "quote_option_2_clarity", color: "quote_option_2_color", price: "quote_option_2_price_18k" },
  { clarity: "quote_option_3_clarity", color: "quote_option_3_color", price: "quote_option_3_price_18k" },
];

export const QUOTE_PRICE_FIELDS = new Set(QUOTE_OPTION_FIELDS.map((option) => option.price));
export const QUOTE_PRICING_FIELDS = new Set([
  "metal",
  "metal_weight",
  "stone_weight",
  "diamond_breakdown",
  "timeline",
  "timeline_adjustment_weeks",
  "quote_discount_type",
  "quote_discount_percent",
  ...QUOTE_OPTION_FIELDS.flatMap((option) => [option.clarity, option.color]),
]);
